namespace Fubu.Inventory.DB
{
	public enum ItemSpecialEffect
	{
		none = 0,
		punchRange = 1,
		skillDamageBonus = 2,
		critDamageIncrease = 3,
		critChanceIncrease = 4,
		knockbackIncrase = 5,
		shieldIncrease = 6,
		gainDefenceAfterKillingEnemies = 7,
		massiveShieldHealDrop = 8,
		damageIncreaseBelowHP = 9,
		burnDamageBonus = 10,
		burnDurationBonus = 11,
		burnStackLimitIncrease = 12,
		freezeDamageBonus = 13,
		freezeDurationBonus = 14,
		lightningDamageBonus = 15,
		lightningDurationBonus = 16,
		lightningSkillsDamageBonus = 17,
		lightningStunDurationFirstTime = 18,
		damageBossBonus = 19,
		extraArm = 20,
		eachExtraArmIncreasePunchDamage = 21,
		eachExtraArmIncreaseDefence = 22,
		eachExtraArmIncreaseCritDamage = 23,
		eachExtraArmIncreaseSkillDamages = 24,
		goldGainFromEnemies = 25,
		comboMetersDrainRate = 26,
		extraDamageComboMeters = 27,
		punchRateIncreaseComboMeterx5s = 28,
		gainShieldComboReachedx3 = 29,
		comboMeterDrainSlower = 30,
		receivedDamageReduceBelowHP = 31,
		freezingEnemiesRestoreHP = 32,
		reviveWithHpAfterDeath = 33,
		receivedDamageReducer = 34,
		levelUpsRestore = 35,
		punchCountDecreasedSkillActivation = 36,
		instantKillNonElitEnemies = 37,
		reflectReceivedDamageToAttacker = 38,
		decatingHealthInsteadofDying = 39
	}
}
